spring.application.name=auth-user-service

# Database Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Shared Settings
spring.jpa.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Default Active Profile
 spring.profiles.active=dev


server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/auth_user_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka ? register this service so others can find it

eureka.client.service-url.defaultZone=http://eureka:eureka123@localhost:8761/eureka
